# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22ee29ddb63c252123ad1cc70fd7991f7eeca7cb7848afdbd5566f12113447a182954c0d8350ebd81f8308fc17d8a9fa398035e1f6f22dc657f57a4df60353b3

test:
  secret_key_base: c5fc499bfb5f9a49b0f41e9f3e70274d7dbcb8e1d5a22ff56fdf412aa5a2f92009880e1107d9065d3260ffe70e9d8fb58e366ad2d3bc186938e0770229a0d8b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
